#ifndef TreeSub_h
#define TreeSub_h

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>

#include <vector>
#include <iostream>
#include <fstream>

using namespace std;

namespace LTANA
{   

class TreeSub {
public :
   TChain         *fChain;   //!pointer to the analyzed TTree or TChain
   Int_t           fCurrent; //!current Tree number in a TChain

// Fixed size dimensions of array or collections stored in the TTree if any.

   // Declaration of leaf types
   Int_t           FatJetInfo_nJet;
   Float_t         FatJetInfo_Jet_pt[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_genpt[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_residual[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_area[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_jes[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_eta[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_phi[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_mass[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_ntracks[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nseltracks[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_flavour[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nbHadrons[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_ncHadrons[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_Ip2N[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_Ip2P[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_Ip3N[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_Ip3P[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_ProbaN[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_ProbaP[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_Proba[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_BprobN[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_BprobP[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_Bprob[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_SvxN[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_Svx[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_SvxNHP[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_SvxHP[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_CombSvxN[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_CombSvxP[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_CombSvx[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_CombIVF[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_CombIVF_P[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_CombIVF_N[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_SoftMuN[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_SoftMuP[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_SoftMu[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_SoftElN[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_SoftElP[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_SoftEl[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_DoubleSV[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_cMVA[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_cMVAv2[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_hist1[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_hist2[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_hist3[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_histJet[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_histSvx[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_SV_multi[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nSM[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nSE[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_looseID[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_tightID[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nFirstSE[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nLastSE[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_nPFElectron;
   Int_t           FatJetInfo_PFElectron_IdxJet[1000];   //[FatJetInfo.nPFElectron]
   Float_t         FatJetInfo_PFElectron_pt[1000];   //[FatJetInfo.nPFElectron]
   Float_t         FatJetInfo_PFElectron_eta[1000];   //[FatJetInfo.nPFElectron]
   Float_t         FatJetInfo_PFElectron_phi[1000];   //[FatJetInfo.nPFElectron]
   Float_t         FatJetInfo_PFElectron_ptrel[1000];   //[FatJetInfo.nPFElectron]
   Float_t         FatJetInfo_PFElectron_deltaR[1000];   //[FatJetInfo.nPFElectron]
   Float_t         FatJetInfo_PFElectron_ratio[1000];   //[FatJetInfo.nPFElectron]
   Float_t         FatJetInfo_PFElectron_ratioRel[1000];   //[FatJetInfo.nPFElectron]
   Float_t         FatJetInfo_PFElectron_IP[1000];   //[FatJetInfo.nPFElectron]
   Float_t         FatJetInfo_PFElectron_IP2D[1000];   //[FatJetInfo.nPFElectron]
   Int_t           FatJetInfo_Jet_nFirstSM[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nLastSM[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_nPFMuon;
   Int_t           FatJetInfo_PFMuon_IdxJet[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_nMuHit[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_nTkHit[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_nPixHit[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_nOutHit[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_nTkLwM[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_nPixLwM[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_nMatched[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_chi2[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_chi2Tk[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_isGlobal[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_hist[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_pt[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_eta[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_phi[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_ptrel[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_deltaR[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_ratio[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_ratioRel[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_IP[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_IP2D[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_IPsig[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_IP2Dsig[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_PFMuon_dz[1000];   //[FatJetInfo.nPFMuon]
   Int_t           FatJetInfo_PFMuon_GoodQuality[1000];   //[FatJetInfo.nPFMuon]
   Float_t         FatJetInfo_Jet_ptSoftDrop[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_etaSoftDrop[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_phiSoftDrop[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_massSoftDrop[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_jecF0SoftDrop[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_ptPruned[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_etaPruned[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_phiPruned[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_massPruned[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_jecF0Pruned[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tauAxis1_px[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tauAxis1_py[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tauAxis1_pz[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tauAxis2_px[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tauAxis2_py[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tauAxis2_pz[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_z_ratio[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_nTracks_fat[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_nSV_fat[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_trackEtaRel_2[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_trackEtaRel_1[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_trackEtaRel_0[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_trackEtaRel_0[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_trackEtaRel_1[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_trackEtaRel_2[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_trackEtaRel_0[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_trackEtaRel_1[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_trackEtaRel_2[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_nSecondaryVertices[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_nSecondaryVertices[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_flightDistance2dSig[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_flightDistance2dSig[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_vertexDeltaR[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_vertexDeltaR[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_vertexEnergyRatio[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_vertexEnergyRatio[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_vertexMass[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_vertexMass[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_vertexMass_corrected[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_vertexMass_corrected[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau1_vertexNTracks[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_tau2_vertexNTracks[1000];   //[FatJetInfo.nJet]
   Float_t         FatJetInfo_Jet_BDTG_SV[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nSubJets_SoftDrop[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nFirstSJ_SoftDrop[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nLastSJ_SoftDrop[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nsharedtracks_SoftDrop[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nsubjettracks_SoftDrop[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nsharedsubjettracks_SoftDrop[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_nSubJet_SoftDrop;
   Int_t           FatJetInfo_SubJetIdx_SoftDrop[1000];   //[FatJetInfo.nSubJet_SoftDrop]
   Int_t           SoftDropSubJetInfo_nJet;
   Float_t         SoftDropSubJetInfo_Jet_pt[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_genpt[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_residual[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_area[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_jes[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_eta[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_phi[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_mass[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_ntracks[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_nseltracks[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_flavour[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_nbHadrons[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_ncHadrons[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_Ip2N[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_Ip2P[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_Ip3N[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_Ip3P[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_ProbaN[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_ProbaP[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_Proba[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_BprobN[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_BprobP[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_Bprob[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_SvxN[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_Svx[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_SvxNHP[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_SvxHP[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_CombSvxN[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_CombSvxP[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_CombSvx[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_CombIVF[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_CombIVF_P[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_CombIVF_N[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_SoftMuN[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_SoftMuP[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_SoftMu[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_SoftElN[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_SoftElP[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_SoftEl[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_DoubleSV[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_cMVA[1000];   //[SoftDropSubJetInfo.nJet]
   Float_t         SoftDropSubJetInfo_Jet_cMVAv2[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_hist1[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_hist2[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_hist3[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_histJet[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_histSvx[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_SV_multi[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_nSM[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_nSE[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_looseID[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_tightID[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_nFirstSE[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_nLastSE[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_nPFElectron;
   Int_t           SoftDropSubJetInfo_PFElectron_IdxJet[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Float_t         SoftDropSubJetInfo_PFElectron_pt[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Float_t         SoftDropSubJetInfo_PFElectron_eta[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Float_t         SoftDropSubJetInfo_PFElectron_phi[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Float_t         SoftDropSubJetInfo_PFElectron_ptrel[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Float_t         SoftDropSubJetInfo_PFElectron_deltaR[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Float_t         SoftDropSubJetInfo_PFElectron_ratio[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Float_t         SoftDropSubJetInfo_PFElectron_ratioRel[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Float_t         SoftDropSubJetInfo_PFElectron_IP[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Float_t         SoftDropSubJetInfo_PFElectron_IP2D[1000];   //[SoftDropSubJetInfo.nPFElectron]
   Int_t           SoftDropSubJetInfo_Jet_nFirstSM[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_Jet_nLastSM[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           SoftDropSubJetInfo_nPFMuon;
   Int_t           SoftDropSubJetInfo_PFMuon_IdxJet[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_nMuHit[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_nTkHit[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_nPixHit[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_nOutHit[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_nTkLwM[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_nPixLwM[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_nMatched[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_chi2[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_chi2Tk[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_isGlobal[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_hist[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_pt[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_eta[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_phi[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_ptrel[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_deltaR[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_ratio[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_ratioRel[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_IP[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_IP2D[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_IPsig[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_IP2Dsig[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Float_t         SoftDropSubJetInfo_PFMuon_dz[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_PFMuon_GoodQuality[1000];   //[SoftDropSubJetInfo.nPFMuon]
   Int_t           SoftDropSubJetInfo_Jet_FatJetIdx[1000];   //[SoftDropSubJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nSubJets_Pruned[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nFirstSJ_Pruned[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nLastSJ_Pruned[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nsharedtracks_Pruned[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nsubjettracks_Pruned[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_Jet_nsharedsubjettracks_Pruned[1000];   //[FatJetInfo.nJet]
   Int_t           FatJetInfo_nSubJet_Pruned;
   Int_t           FatJetInfo_SubJetIdx_Pruned[1000];   //[FatJetInfo.nSubJet_Pruned]
   Int_t           PrunedSubJetInfo_nJet;
   Float_t         PrunedSubJetInfo_Jet_pt[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_genpt[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_residual[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_area[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_jes[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_eta[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_phi[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_mass[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_ntracks[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_nseltracks[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_flavour[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_nbHadrons[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_ncHadrons[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_Ip2N[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_Ip2P[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_Ip3N[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_Ip3P[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_ProbaN[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_ProbaP[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_Proba[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_BprobN[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_BprobP[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_Bprob[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_SvxN[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_Svx[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_SvxNHP[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_SvxHP[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_CombSvxN[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_CombSvxP[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_CombSvx[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_CombIVF[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_CombIVF_P[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_CombIVF_N[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_SoftMuN[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_SoftMuP[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_SoftMu[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_SoftElN[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_SoftElP[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_SoftEl[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_DoubleSV[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_cMVA[1000];   //[PrunedSubJetInfo.nJet]
   Float_t         PrunedSubJetInfo_Jet_cMVAv2[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_hist1[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_hist2[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_hist3[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_histJet[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_histSvx[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_SV_multi[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_nSM[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_nSE[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_looseID[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_tightID[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_nFirstSE[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_nLastSE[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_nPFElectron;
   Int_t           PrunedSubJetInfo_PFElectron_IdxJet[1000];   //[PrunedSubJetInfo.nPFElectron]
   Float_t         PrunedSubJetInfo_PFElectron_pt[1000];   //[PrunedSubJetInfo.nPFElectron]
   Float_t         PrunedSubJetInfo_PFElectron_eta[1000];   //[PrunedSubJetInfo.nPFElectron]
   Float_t         PrunedSubJetInfo_PFElectron_phi[1000];   //[PrunedSubJetInfo.nPFElectron]
   Float_t         PrunedSubJetInfo_PFElectron_ptrel[1000];   //[PrunedSubJetInfo.nPFElectron]
   Float_t         PrunedSubJetInfo_PFElectron_deltaR[1000];   //[PrunedSubJetInfo.nPFElectron]
   Float_t         PrunedSubJetInfo_PFElectron_ratio[1000];   //[PrunedSubJetInfo.nPFElectron]
   Float_t         PrunedSubJetInfo_PFElectron_ratioRel[1000];   //[PrunedSubJetInfo.nPFElectron]
   Float_t         PrunedSubJetInfo_PFElectron_IP[1000];   //[PrunedSubJetInfo.nPFElectron]
   Float_t         PrunedSubJetInfo_PFElectron_IP2D[1000];   //[PrunedSubJetInfo.nPFElectron]
   Int_t           PrunedSubJetInfo_Jet_nFirstSM[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_Jet_nLastSM[1000];   //[PrunedSubJetInfo.nJet]
   Int_t           PrunedSubJetInfo_nPFMuon;
   Int_t           PrunedSubJetInfo_PFMuon_IdxJet[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_nMuHit[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_nTkHit[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_nPixHit[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_nOutHit[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_nTkLwM[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_nPixLwM[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_nMatched[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_chi2[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_chi2Tk[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_isGlobal[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_hist[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_pt[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_eta[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_phi[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_ptrel[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_deltaR[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_ratio[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_ratioRel[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_IP[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_IP2D[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_IPsig[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_IP2Dsig[1000];   //[PrunedSubJetInfo.nPFMuon]
   Float_t         PrunedSubJetInfo_PFMuon_dz[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_PFMuon_GoodQuality[1000];   //[PrunedSubJetInfo.nPFMuon]
   Int_t           PrunedSubJetInfo_Jet_FatJetIdx[1000];   //[PrunedSubJetInfo.nJet]

   // List of branches
   TBranch        *b_FatJetInfo_nJet;   //!
   TBranch        *b_FatJetInfo_Jet_pt;   //!
   TBranch        *b_FatJetInfo_Jet_genpt;   //!
   TBranch        *b_FatJetInfo_Jet_residual;   //!
   TBranch        *b_FatJetInfo_Jet_area;   //!
   TBranch        *b_FatJetInfo_Jet_jes;   //!
   TBranch        *b_FatJetInfo_Jet_eta;   //!
   TBranch        *b_FatJetInfo_Jet_phi;   //!
   TBranch        *b_FatJetInfo_Jet_mass;   //!
   TBranch        *b_FatJetInfo_Jet_ntracks;   //!
   TBranch        *b_FatJetInfo_Jet_nseltracks;   //!
   TBranch        *b_FatJetInfo_Jet_flavour;   //!
   TBranch        *b_FatJetInfo_Jet_nbHadrons;   //!
   TBranch        *b_FatJetInfo_Jet_ncHadrons;   //!
   TBranch        *b_FatJetInfo_Jet_Ip2N;   //!
   TBranch        *b_FatJetInfo_Jet_Ip2P;   //!
   TBranch        *b_FatJetInfo_Jet_Ip3N;   //!
   TBranch        *b_FatJetInfo_Jet_Ip3P;   //!
   TBranch        *b_FatJetInfo_Jet_ProbaN;   //!
   TBranch        *b_FatJetInfo_Jet_ProbaP;   //!
   TBranch        *b_FatJetInfo_Jet_Proba;   //!
   TBranch        *b_FatJetInfo_Jet_BprobN;   //!
   TBranch        *b_FatJetInfo_Jet_BprobP;   //!
   TBranch        *b_FatJetInfo_Jet_Bprob;   //!
   TBranch        *b_FatJetInfo_Jet_SvxN;   //!
   TBranch        *b_FatJetInfo_Jet_Svx;   //!
   TBranch        *b_FatJetInfo_Jet_SvxNHP;   //!
   TBranch        *b_FatJetInfo_Jet_SvxHP;   //!
   TBranch        *b_FatJetInfo_Jet_CombSvxN;   //!
   TBranch        *b_FatJetInfo_Jet_CombSvxP;   //!
   TBranch        *b_FatJetInfo_Jet_CombSvx;   //!
   TBranch        *b_FatJetInfo_Jet_CombIVF;   //!
   TBranch        *b_FatJetInfo_Jet_CombIVF_P;   //!
   TBranch        *b_FatJetInfo_Jet_CombIVF_N;   //!
   TBranch        *b_FatJetInfo_Jet_SoftMuN;   //!
   TBranch        *b_FatJetInfo_Jet_SoftMuP;   //!
   TBranch        *b_FatJetInfo_Jet_SoftMu;   //!
   TBranch        *b_FatJetInfo_Jet_SoftElN;   //!
   TBranch        *b_FatJetInfo_Jet_SoftElP;   //!
   TBranch        *b_FatJetInfo_Jet_SoftEl;   //!
   TBranch        *b_FatJetInfo_Jet_DoubleSV;   //!
   TBranch        *b_FatJetInfo_Jet_cMVA;   //!
   TBranch        *b_FatJetInfo_Jet_cMVAv2;   //!
   TBranch        *b_FatJetInfo_Jet_hist1;   //!
   TBranch        *b_FatJetInfo_Jet_hist2;   //!
   TBranch        *b_FatJetInfo_Jet_hist3;   //!
   TBranch        *b_FatJetInfo_Jet_histJet;   //!
   TBranch        *b_FatJetInfo_Jet_histSvx;   //!
   TBranch        *b_FatJetInfo_Jet_SV_multi;   //!
   TBranch        *b_FatJetInfo_Jet_nSM;   //!
   TBranch        *b_FatJetInfo_Jet_nSE;   //!
   TBranch        *b_FatJetInfo_Jet_looseID;   //!
   TBranch        *b_FatJetInfo_Jet_tightID;   //!
   TBranch        *b_FatJetInfo_Jet_nFirstSE;   //!
   TBranch        *b_FatJetInfo_Jet_nLastSE;   //!
   TBranch        *b_FatJetInfo_nPFElectron;   //!
   TBranch        *b_FatJetInfo_PFElectron_IdxJet;   //!
   TBranch        *b_FatJetInfo_PFElectron_pt;   //!
   TBranch        *b_FatJetInfo_PFElectron_eta;   //!
   TBranch        *b_FatJetInfo_PFElectron_phi;   //!
   TBranch        *b_FatJetInfo_PFElectron_ptrel;   //!
   TBranch        *b_FatJetInfo_PFElectron_deltaR;   //!
   TBranch        *b_FatJetInfo_PFElectron_ratio;   //!
   TBranch        *b_FatJetInfo_PFElectron_ratioRel;   //!
   TBranch        *b_FatJetInfo_PFElectron_IP;   //!
   TBranch        *b_FatJetInfo_PFElectron_IP2D;   //!
   TBranch        *b_FatJetInfo_Jet_nFirstSM;   //!
   TBranch        *b_FatJetInfo_Jet_nLastSM;   //!
   TBranch        *b_FatJetInfo_nPFMuon;   //!
   TBranch        *b_FatJetInfo_PFMuon_IdxJet;   //!
   TBranch        *b_FatJetInfo_PFMuon_nMuHit;   //!
   TBranch        *b_FatJetInfo_PFMuon_nTkHit;   //!
   TBranch        *b_FatJetInfo_PFMuon_nPixHit;   //!
   TBranch        *b_FatJetInfo_PFMuon_nOutHit;   //!
   TBranch        *b_FatJetInfo_PFMuon_nTkLwM;   //!
   TBranch        *b_FatJetInfo_PFMuon_nPixLwM;   //!
   TBranch        *b_FatJetInfo_PFMuon_nMatched;   //!
   TBranch        *b_FatJetInfo_PFMuon_chi2;   //!
   TBranch        *b_FatJetInfo_PFMuon_chi2Tk;   //!
   TBranch        *b_FatJetInfo_PFMuon_isGlobal;   //!
   TBranch        *b_FatJetInfo_PFMuon_hist;   //!
   TBranch        *b_FatJetInfo_PFMuon_pt;   //!
   TBranch        *b_FatJetInfo_PFMuon_eta;   //!
   TBranch        *b_FatJetInfo_PFMuon_phi;   //!
   TBranch        *b_FatJetInfo_PFMuon_ptrel;   //!
   TBranch        *b_FatJetInfo_PFMuon_deltaR;   //!
   TBranch        *b_FatJetInfo_PFMuon_ratio;   //!
   TBranch        *b_FatJetInfo_PFMuon_ratioRel;   //!
   TBranch        *b_FatJetInfo_PFMuon_IP;   //!
   TBranch        *b_FatJetInfo_PFMuon_IP2D;   //!
   TBranch        *b_FatJetInfo_PFMuon_IPsig;   //!
   TBranch        *b_FatJetInfo_PFMuon_IP2Dsig;   //!
   TBranch        *b_FatJetInfo_PFMuon_dz;   //!
   TBranch        *b_FatJetInfo_PFMuon_GoodQuality;   //!
   TBranch        *b_FatJetInfo_Jet_ptSoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_etaSoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_phiSoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_massSoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_jecF0SoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_ptPruned;   //!
   TBranch        *b_FatJetInfo_Jet_etaPruned;   //!
   TBranch        *b_FatJetInfo_Jet_phiPruned;   //!
   TBranch        *b_FatJetInfo_Jet_massPruned;   //!
   TBranch        *b_FatJetInfo_Jet_jecF0Pruned;   //!
   TBranch        *b_FatJetInfo_Jet_tau1;   //!
   TBranch        *b_FatJetInfo_Jet_tau2;   //!
   TBranch        *b_FatJetInfo_Jet_tauAxis1_px;   //!
   TBranch        *b_FatJetInfo_Jet_tauAxis1_py;   //!
   TBranch        *b_FatJetInfo_Jet_tauAxis1_pz;   //!
   TBranch        *b_FatJetInfo_Jet_tauAxis2_px;   //!
   TBranch        *b_FatJetInfo_Jet_tauAxis2_py;   //!
   TBranch        *b_FatJetInfo_Jet_tauAxis2_pz;   //!
   TBranch        *b_FatJetInfo_Jet_z_ratio;   //!
   TBranch        *b_FatJetInfo_Jet_nTracks_fat;   //!
   TBranch        *b_FatJetInfo_Jet_nSV_fat;   //!
   TBranch        *b_FatJetInfo_Jet_trackEtaRel_2;   //!
   TBranch        *b_FatJetInfo_Jet_trackEtaRel_1;   //!
   TBranch        *b_FatJetInfo_Jet_trackEtaRel_0;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_trackEtaRel_0;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_trackEtaRel_1;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_trackEtaRel_2;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_trackEtaRel_0;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_trackEtaRel_1;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_trackEtaRel_2;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_nSecondaryVertices;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_nSecondaryVertices;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_flightDistance2dSig;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_flightDistance2dSig;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_vertexDeltaR;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_vertexDeltaR;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_vertexEnergyRatio;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_vertexEnergyRatio;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_vertexMass;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_vertexMass;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_vertexMass_corrected;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_vertexMass_corrected;   //!
   TBranch        *b_FatJetInfo_Jet_tau1_vertexNTracks;   //!
   TBranch        *b_FatJetInfo_Jet_tau2_vertexNTracks;   //!
   TBranch        *b_FatJetInfo_Jet_BDTG_SV;   //!
   TBranch        *b_FatJetInfo_Jet_nSubJets_SoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_nFirstSJ_SoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_nLastSJ_SoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_nsharedtracks_SoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_nsubjettracks_SoftDrop;   //!
   TBranch        *b_FatJetInfo_Jet_nsharedsubjettracks_SoftDrop;   //!
   TBranch        *b_FatJetInfo_nSubJet_SoftDrop;   //!
   TBranch        *b_FatJetInfo_SubJetIdx_SoftDrop;   //!
   TBranch        *b_SoftDropSubJetInfo_nJet;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_pt;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_genpt;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_residual;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_area;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_jes;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_eta;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_phi;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_mass;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_ntracks;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_nseltracks;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_flavour;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_nbHadrons;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_ncHadrons;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_Ip2N;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_Ip2P;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_Ip3N;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_Ip3P;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_ProbaN;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_ProbaP;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_Proba;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_BprobN;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_BprobP;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_Bprob;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SvxN;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_Svx;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SvxNHP;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SvxHP;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_CombSvxN;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_CombSvxP;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_CombSvx;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_CombIVF;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_CombIVF_P;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_CombIVF_N;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SoftMuN;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SoftMuP;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SoftMu;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SoftElN;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SoftElP;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SoftEl;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_DoubleSV;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_cMVA;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_cMVAv2;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_hist1;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_hist2;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_hist3;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_histJet;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_histSvx;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_SV_multi;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_nSM;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_nSE;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_looseID;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_tightID;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_nFirstSE;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_nLastSE;   //!
   TBranch        *b_SoftDropSubJetInfo_nPFElectron;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_IdxJet;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_pt;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_eta;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_phi;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_ptrel;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_deltaR;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_ratio;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_ratioRel;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_IP;   //!
   TBranch        *b_SoftDropSubJetInfo_PFElectron_IP2D;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_nFirstSM;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_nLastSM;   //!
   TBranch        *b_SoftDropSubJetInfo_nPFMuon;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_IdxJet;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_nMuHit;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_nTkHit;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_nPixHit;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_nOutHit;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_nTkLwM;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_nPixLwM;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_nMatched;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_chi2;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_chi2Tk;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_isGlobal;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_hist;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_pt;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_eta;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_phi;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_ptrel;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_deltaR;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_ratio;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_ratioRel;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_IP;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_IP2D;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_IPsig;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_IP2Dsig;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_dz;   //!
   TBranch        *b_SoftDropSubJetInfo_PFMuon_GoodQuality;   //!
   TBranch        *b_SoftDropSubJetInfo_Jet_FatJetIdx;   //!
   TBranch        *b_FatJetInfo_Jet_nSubJets_Pruned;   //!
   TBranch        *b_FatJetInfo_Jet_nFirstSJ_Pruned;   //!
   TBranch        *b_FatJetInfo_Jet_nLastSJ_Pruned;   //!
   TBranch        *b_FatJetInfo_Jet_nsharedtracks_Pruned;   //!
   TBranch        *b_FatJetInfo_Jet_nsubjettracks_Pruned;   //!
   TBranch        *b_FatJetInfo_Jet_nsharedsubjettracks_Pruned;   //!
   TBranch        *b_FatJetInfo_nSubJet_Pruned;   //!
   TBranch        *b_FatJetInfo_SubJetIdx_Pruned;   //!
   TBranch        *b_PrunedSubJetInfo_nJet;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_pt;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_genpt;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_residual;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_area;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_jes;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_eta;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_phi;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_mass;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_ntracks;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_nseltracks;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_flavour;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_nbHadrons;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_ncHadrons;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_Ip2N;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_Ip2P;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_Ip3N;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_Ip3P;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_ProbaN;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_ProbaP;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_Proba;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_BprobN;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_BprobP;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_Bprob;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SvxN;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_Svx;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SvxNHP;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SvxHP;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_CombSvxN;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_CombSvxP;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_CombSvx;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_CombIVF;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_CombIVF_P;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_CombIVF_N;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SoftMuN;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SoftMuP;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SoftMu;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SoftElN;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SoftElP;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SoftEl;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_DoubleSV;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_cMVA;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_cMVAv2;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_hist1;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_hist2;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_hist3;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_histJet;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_histSvx;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_SV_multi;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_nSM;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_nSE;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_looseID;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_tightID;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_nFirstSE;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_nLastSE;   //!
   TBranch        *b_PrunedSubJetInfo_nPFElectron;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_IdxJet;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_pt;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_eta;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_phi;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_ptrel;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_deltaR;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_ratio;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_ratioRel;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_IP;   //!
   TBranch        *b_PrunedSubJetInfo_PFElectron_IP2D;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_nFirstSM;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_nLastSM;   //!
   TBranch        *b_PrunedSubJetInfo_nPFMuon;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_IdxJet;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_nMuHit;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_nTkHit;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_nPixHit;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_nOutHit;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_nTkLwM;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_nPixLwM;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_nMatched;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_chi2;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_chi2Tk;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_isGlobal;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_hist;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_pt;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_eta;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_phi;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_ptrel;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_deltaR;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_ratio;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_ratioRel;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_IP;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_IP2D;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_IPsig;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_IP2Dsig;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_dz;   //!
   TBranch        *b_PrunedSubJetInfo_PFMuon_GoodQuality;   //!
   TBranch        *b_PrunedSubJetInfo_Jet_FatJetIdx;   //!

   TreeSub(TChain *ch=0,char* fname="physics.root",std::string treename="physics");
   virtual ~TreeSub();
   virtual Int_t    GetEntry(Long64_t entry);
   virtual Long64_t LoadTree(Long64_t entry);
   virtual void     Init(TChain *tree);
   virtual void     registerInputBranches(TChain *tree);
};
   
}

#endif
